### ISSUE TITLE
Update with latest Font Awesome icon set

### ISSUE THREAD

**Issue by NCLAMB** [chrisadipascual/FontAwesome-Icons-Dropdown-Umbraco-Plugin#2]
Hi, I've downloaded the source code to your excellent plugin, and try to update the Font Awesome to the latest set, but when I try uploading this to replace the existing package, it doesn't update, is there anything that I am missing?

**Comment by chrisadipascual** [comment]
You need to replace the values on the controller

**Comment by chrisadipascual** [comment]
https://our.umbraco.org/forum/developing-packages/76765-font-awesome-icons-dropdown-for-umbraco-7-updated-for-font-awesome-verson-461

**Comment by chrisadipascual** [comment]
https://docs.google.com/spreadsheets/d/1d_ag6mxBXLxHoBMqYpMyD9aU9es8m-UF6GOT-9JusL0/edit#gid=0
