### ISSUE TITLE
Razor Sample is not correct

### ISSUE THREAD

**Issue by bjarnef** [chrisadipascual/FontAwesome-Icons-Dropdown-Umbraco-Plugin#3]
The razor sample on our.umbraco.org says:

```
<i class="fa fa-@Model.Content.GetPropertyValue("yourAlias")"></i>
```

but the value saved is saved in format e.g. `fa-hdd-o`.

therefore the correct code example is:

```
<i class="fa @Model.Content.GetPropertyValue("yourAlias")"></i>
```

or usually you also want to add aria-hidden="true" to prevent screen readers from reading the text.

**Comment by chrisadipascual** [comment]
Dear Bjarne,

Thanks for pointing that out! I'll correct the sample when we get the
chance. Many thanks for your valued input.

**Comment by chrisadipascual** [comment]
Razor sample has been updated~
