### ISSUE TITLE
ModelsBuilder

### ISSUE THREAD

**Issue by madebybear** [chrisadipascual/FontAwesome-Icons-Dropdown-Umbraco-Plugin#4]
Hi!

Great package! Thanks! 

I found a small issue when using this with UmbracoModelsBuilder. When I generated my models, the generated type defaulted to `JToken`, rather than a string. Don't know why. No matter though, because here's a simple property converter;

 
    using System;
	using Umbraco.Core.Models.PublishedContent;
	using Umbraco.Core.PropertyEditors;

	namespace Need.A.Namespace
	{
		public class FontAwesomeIconsDropdownPropertyConverter : PropertyValueConverterBase, IPropertyValueConverterMeta
		{
			public PropertyCacheLevel GetPropertyCacheLevel(PublishedPropertyType propertyType, PropertyCacheValue cacheValue)
			{
				return PropertyCacheLevel.Content;
			}

			public override object ConvertSourceToObject(PublishedPropertyType propertyType, object source, bool preview)
			{
				// guard; no source
				if (source == null)
					return string.Empty;

				return source.ToString();
			}

			public override bool IsConverter(PublishedPropertyType propertyType)
			{
				return propertyType.PropertyEditorAlias.ToLower().Equals("fontawesomeiconsdd");
			}

			public Type GetPropertyValueType(PublishedPropertyType propertyType)
			{
				return typeof(string);
			}
		}
	}

Feel free to include this in your project for the next release. 👍

**Comment by chrisadipascual** [comment]
Thanks for the code/feedback! Will look into it when we get the time
